import type { Metadata } from "next";
import "@trussworks/react-uswds/lib/uswds.css";
import "@trussworks/react-uswds/lib/index.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { GovBanner } from '@trussworks/react-uswds';
import HeaderWrapper from "@/components/HeaderWrapper";
import LocaleProvider from "@/context/LocaleContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <LocaleProvider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {/* <GovBanner /> */}
          <HeaderWrapper />
          {children}
        </body>
      </LocaleProvider>
    </html>
  );
}
